web_8080: python3 -m bottle api --bind=localhost:8080 --reload --debug
userApi_8081: python3 -m bottle user_services --bind=localhost:8081 --reload --debug
timelineApi_8082: python3 -m bottle timeline_services --bind=localhost:8082 --reload --debug

